// <auto-generated />
using System;
using EmailService.Infrastructure.Postgres.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmailService.Infrastructure.Postgres.Data.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    partial class EmailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmailService.Infrastructure.Postgres.Data.Entities.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("from");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean")
                        .HasColumnName("is_html");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_email_outbox_message_id");

                    b.HasIndex("StatusId", "NextAttemptAt")
                        .HasDatabaseName("ix_email_outbox_status_id_next_attempt_at");

                    b.ToTable("email_outbox", (string)null);
                });

            modelBuilder.Entity("EmailService.Infrastructure.Postgres.Data.Entities.EmailOutboxStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_outbox_statuses");

                    b.ToTable("outbox_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 1,
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sent"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("EmailService.Infrastructure.Postgres.Data.Entities.EmailOutbox", b =>
                {
                    b.HasOne("EmailService.Infrastructure.Postgres.Data.Entities.EmailOutboxStatus", "EmailOutboxStatus")
                        .WithMany("EmailOutboxes")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_email_outbox_email_outbox_statuses_status_id");

                    b.Navigation("EmailOutboxStatus");
                });

            modelBuilder.Entity("EmailService.Infrastructure.Postgres.Data.Entities.EmailOutboxStatus", b =>
                {
                    b.Navigation("EmailOutboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
