// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TasksBoard.Infrastructure.Data.Contexts;

#nullable disable

namespace TasksBoard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TasksBoardDbContext))]
    [Migration("20250313133107_UpdateBoardMemberTable")]
    partial class UpdateBoardMemberTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TasksBoard.Domain.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "AccountId")
                        .IsUnique();

                    b.ToTable("boardmembers", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardMemberPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardPermissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BoardMemberId");

                    b.HasIndex("BoardPermissionId");

                    b.ToTable("boardmemberspermissions", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NoticeStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("NoticeStatusId");

                    b.ToTable("boardnotices", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardNoticeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("boardnoticestatuses", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("boardpermissions", (string)null);
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardMember", b =>
                {
                    b.HasOne("TasksBoard.Domain.Entities.Board", "Boards")
                        .WithMany("BoardMembers")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boards");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardMemberPermission", b =>
                {
                    b.HasOne("TasksBoard.Domain.Entities.BoardMember", "BoardMember")
                        .WithMany("BoardMemberPermissions")
                        .HasForeignKey("BoardMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksBoard.Domain.Entities.BoardPermission", "BoardPermission")
                        .WithMany("BoardMemberPermissions")
                        .HasForeignKey("BoardPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardMember");

                    b.Navigation("BoardPermission");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardNotice", b =>
                {
                    b.HasOne("TasksBoard.Domain.Entities.Board", "Board")
                        .WithMany("Notices")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksBoard.Domain.Entities.BoardNoticeStatus", "BoardNoticeStatus")
                        .WithMany("BoardNotices")
                        .HasForeignKey("NoticeStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("BoardNoticeStatus");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.Board", b =>
                {
                    b.Navigation("BoardMembers");

                    b.Navigation("Notices");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardMember", b =>
                {
                    b.Navigation("BoardMemberPermissions");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardNoticeStatus", b =>
                {
                    b.Navigation("BoardNotices");
                });

            modelBuilder.Entity("TasksBoard.Domain.Entities.BoardPermission", b =>
                {
                    b.Navigation("BoardMemberPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
