scrape_configs:
  - job_name: tasksboard.api
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
    - targets: 
        - host.docker.internal:7227
      labels:
        app: tasksboard.local
    - targets:
        - tasksboard.api:9001 
      labels:
        app: tasksboard-docker